# Weights and biases
wandb_run: False
entity : "williamlaplante" #to post results -> 'cs532-2022', to analyze your own stuff -> 'williamlaplante'

# Directory structure
#CPSC532Homeworks
base_dir: "/Users/william/Projects/TTV/foppl/" # NOTE: This path should be relative to the daphne path!
daphne_dir: '../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
#[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
probabilistic_tests: []
#[1,2,3,4,5,6,7,8]
project_programs: [2]

#which HW to run
prog_set: 'project'

# Daphne (re)compilation
compile: False

# Evaluation method
#mode: 'desugar'
mode: 'graph'

# Inference method

inference_methods : ["inference_compilation", "importance_sampling", "MH_gibbs", "HMC"]
num_samples: 1e4

#inference compilation specific parameters
num_traces_training: 1e2 #number of traces the inference compilation engine trains on
batch_size : 5e2 #number of samples used to estimate loss
num_epochs : 3 #number of times we go over the dataset (of size num_traces_training)

save : False

verbose : False