# Weights and biases
wandb_run: False
entity : "williamlaplante" #to post results -> 'cs532-2022', to analyze your own stuff -> 'williamlaplante'

# Directory structure
#CPSC532Homeworks
base_dir: "/Users/william/Projects/TTV/foppl/" # NOTE: This path should be relative to the daphne path!
daphne_dir: '../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
#[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
probabilistic_tests: []
#[1,2,3,4,5,6,7,8]
project_programs: [2]

#which HW to run
prog_set: 'project'

# Daphne (re)compilation
compile: False

# Evaluation method
#mode: 'desugar'
mode: 'graph'

# Inference method

inference_methods : ["inference_compilation"]
#["inference_compilation", "importance_sampling", "MH_gibbs", "HMC"]
num_samples: 1e3

#inference compilation specific parameters
num_traces_training: 1e5 #number of traces the inference compilation engine trains on
batch_size : 400 #number of samples used to estimate loss
num_epochs : 3 #number of times we go over the dataset (of size num_traces_training)
learning_rate : 1e-4
lstm : False

# For program 1 : batch size = 2e2 or 3e2, learning_rate=1e-4, num_epochs=3, num_traces_learning=1e5 works well
# For program 2 : 
#

save : False

verbose : False